-- Create the Reservations table
create table reservations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text not null,
  guests text not null,
  date date not null,
  time time not null,
  requests text,
  status text default 'Pending'
);

-- Create the Contact Messages table
create table contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text not null,
  subject text not null,
  message text not null,
  status text default 'Unread'
);

-- Enable Row Level Security (RLS) - Recommended, but for this specific server-side usage, we will use the Service Role Key to bypass it.
-- However, if you use the Anon Key, you need policies. For simplicity in this robust backend setup, we assume access via Service Role Key
-- or public access for now if you just want it to work easily.

-- Simple policy to allow public insert (for booking) and select (if you were fetching from frontend directly, but we are not).
-- Since we are using a Node backend (server.js), you should use the SERVICE_ROLE_KEY in your .env for full access without policies,
-- OR set up policies if using ANON_KEY.

-- OPTIONAL: If using ANON_KEY in server.js (not recommended for backend writes), run these:
-- alter table reservations enable row level security;
-- create policy "Enable read access for all users" on reservations for select using (true);
-- create policy "Enable insert for all users" on reservations for insert with check (true);
-- create policy "Enable update for all users" on reservations for update using (true);

-- alter table contacts enable row level security;
-- create policy "Enable read access for all users" on contacts for select using (true);
-- create policy "Enable insert for all users" on contacts for insert with check (true);
-- create policy "Enable update for all users" on contacts for update using (true);
